baseURL = "https://danharr.is/"
languageCode = "en-gb"
title = "Dan Harris's Blog"

disableKinds = ["taxonomy", "taxonomyTerm"]

[menu]
  [[menu.main]]
    identifier = "main site"
    name = "Main Website"
    url = "https://danmharris.com"
    weight = 20
  [[menu.main]]
    identifier = "tech blog"
    name = "Tech Blog"
    url = "https://danmharris.com/posts"
    weight = 30

[permalinks]
  post = "/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true
