baseURL = "https://me.danmharris.com/"
languageCode = "en-gb"
title = "Dan Harris's Blog"

[menu]
  [[menu.main]]
    identifier = "main site"
    name = "Main Website"
    url = "https://danmharris.com"
    weight = 20
  [[menu.main]]
    identifier = "tech blog"
    name = "Tech Blog"
    url = "https://blog.danmharris.com"
    weight = 30

[permalinks]
  post = "/:year/:month/:title/"

[blackfriday]
  hrefTargetBlank = true
