version: 2
jobs:
  build:
    docker:
      - image: debian:buster
    working_directory: ~/personal-blog
    steps:
      - checkout
      - run:
          name: Install hugo
          command: apt update && apt install -y hugo
      - run:
          name: Build site
          command: hugo
      - run:
          name: Install CA certificates
          command: apt install -y ca-certificates
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/personal-blog
    steps:
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy to S3
          command: aws s3 sync /tmp/workspace/public s3://danharr.is/ --delete
      - run:
          name: Invalidate cloudfront cache
          command: aws cloudfront create-invalidation --distribution-id E1HZ7YMVH9SL2L --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
